name: Sanitizer PHP Static Analysis

on: [push, pull_request]

jobs:
    analysis:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-version: ["7.1"]

        steps:
            - uses: actions/checkout@v2

            - name: Use PHP ${{matrix.php-version}}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{matrix.php-version}}
                  tools: composer:v2
                  coverage: none

            - name: Update dependencies
              run: composer update

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Find non-standard code formatting
              run: composer run-script lint:check

            - name: Find bugs in code
              run: composer run-script analyse:force
